print("Welcome to the tip calculator.")
bill=input("What was the total bill? $")
percentage=input("What percentage tip would you like to give? 10, 12, or 15? ")
number_of_people=input("How many people to split the bill? ")
pay=(float(bill)+float(bill)*(int(percentage)/100))/int(number_of_people)
final_pay="{:.2f}".format(pay)
print(f"Each person should pay: ${round(pay, 2)}")
print(f"Each person should pay: ${final_pay}")